apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: flaskdemo
  name: flaskdemo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskdemo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flaskdemo
    spec:
      containers:
      - image: superdba111/test:9
        name: flaskdemo
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: flaskdemo
  # Optional: Specify subnets if they are not in the same AZ as your EKS cluster
  # Replace with the actual subnet ids in your desired AZs
  # subnets:
    - subnet-0739b0384785781cc  # Example subnet ID
    - subnet-01b3659c181e7a89b  # Example subnet ID
